const plan = { Monday: ['Flat Chest Press', 'Incline Chest Press', 'Tricep Extensions', 'Push-ups'], Tuesday: ['Leg Curls', 'Stepper', 'Bike Intervals'], Wednesday: ['Light Cardio or Rest'], Thursday: ['Bicep Curls', 'Hammer Curls', 'Forearm Machine', 'Bent-over Rows'], Friday: ['Overhead Press', 'Lateral Raises', 'Plank', 'Crunches'], Saturday: ['Active Recovery'], Sunday: ['Rest'] };

function renderPlan() { const container = document.getElementById('workout-plan'); container.innerHTML = '<h2>Weekly Plan</h2>'; for (const [day, exercises] of Object.entries(plan)) { const section = document.createElement('div'); section.innerHTML = <h3>${day}</h3>; exercises.forEach(exercise => { const form = document.createElement('form'); form.classList.add('exercise-form'); form.innerHTML = <strong>${exercise}</strong><br> Weight (lbs): <input type="number" name="weight" required>  Reps: <input type="number" name="reps" required>  Sets: <input type="number" name="sets" required> <button type="submit">Save</button>; form.onsubmit = function(e) { e.preventDefault(); const formData = new FormData(form); const logEntry = { date: new Date().toLocaleDateString(), day, exercise, weight: formData.get('weight'), reps: formData.get('reps'), sets: formData.get('sets') }; const logs = JSON.parse(localStorage.getItem('detailedWorkoutLogs')) || []; logs.unshift(logEntry); localStorage.setItem('detailedWorkoutLogs', JSON.stringify(logs)); renderLogs(); form.reset(); }; section.appendChild(form); }); container.appendChild(section); } }

function renderLogs() { const logs = JSON.parse(localStorage.getItem('detailedWorkoutLogs')) || []; const list = document.getElementById('log-list'); list.innerHTML = ''; logs.forEach(log => { const item = document.createElement('li'); item.textContent = ${log.date} (${log.day}) – ${log.exercise}: ${log.sets} sets x ${log.reps} reps @ ${log.weight} lbs; list.appendChild(item); }); }

window.onload = () => { renderPlan(); renderLogs(); if ('serviceWorker' in navigator) { navigator.serviceWorker.register('service-worker.js'); } };

                       
